[package]
name = "rustache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
glob = "0.3.1"
rayon = "1.10.0"
substring = "1.4.5"
thiserror = "1.0.58"
